
name: Publicar no Docker

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Step 2: Set up Docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Step 3: Log in to Docker Hub (or GitHub Container Registry)
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME  }}
                password: ${{ secrets.DOCKER_PASSWORD  }}

             # Step 4: Determine version tag dynamically
            - name: Determine image tag
              id: versioning
              run: |
                if [ "${{ github.ref }}" == "refs/heads/main" ]; then
                    echo "tag=latest" >> $GITHUB_ENV
                else
                    BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
                    echo "tag=$BRANCH_NAME" >> $GITHUB_ENV
                fi
                echo "version=commit-${{ github.sha }}" >> $GITHUB_ENV

            # Step 4: Build and push the Docker image
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: |
                    mrpauloii/snapcast-processamento:latest
                context: .
            


            